version: "3.9"
volumes:
  mariadb:
services:
  web:
    build: .
    volumes:
      - .composer:/root/.composer
      - ../php:/var/www/html
    working_dir: /var/www/html
    extra_hosts:
      - "docker.host.internal:host-gateway"
    environment:
      - PHP_INI_DIR=/usr/local/etc/php/conf.d/
    ports:
      - 80:80
    links:
      - mariadb
  mariadb:
    image: mariadb:latest
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mewj8mtn"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "remote"
      MYSQL_PASSWORD: "782kEW17"
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - '8888:80'
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: mewj8mtn


